import {
  COMPONENT_MANIFEST_SCHEMA_VERSION as CONTRACTS_COMPONENT_MANIFEST_SCHEMA_VERSION,
  COMPONENT_STANDARD_SOURCE_HASH as CONTRACTS_COMPONENT_STANDARD_SOURCE_HASH,
  COMPONENT_STANDARD_VERSION as CONTRACTS_COMPONENT_STANDARD_VERSION,
} from '@promptframe/contracts';

export const COMPONENT_STANDARD_VERSION = CONTRACTS_COMPONENT_STANDARD_VERSION;
export const COMPONENT_STANDARD_SOURCE_HASH = CONTRACTS_COMPONENT_STANDARD_SOURCE_HASH;
export const COMPONENT_STANDARD_SOURCE_PATH = 'https://github.com/ty-teams/promptframe-component-authoring#readme' as const;
export const COMPONENT_KIT_VERSION = '0.1.7' as const;
export const COMPONENT_MANIFEST_SCHEMA_VERSION = CONTRACTS_COMPONENT_MANIFEST_SCHEMA_VERSION;
export const COMPONENT_REVIEW_CHECKLIST_VERSION = 'component-review-checklist.v0.1.0' as const;

export function getComponentStandardStamp() {
  return {
    sourceVersion: COMPONENT_STANDARD_VERSION,
    sourceHash: COMPONENT_STANDARD_SOURCE_HASH,
    sourcePath: COMPONENT_STANDARD_SOURCE_PATH,
    componentKitVersion: COMPONENT_KIT_VERSION,
    manifestSchemaVersion: COMPONENT_MANIFEST_SCHEMA_VERSION,
    reviewChecklistVersion: COMPONENT_REVIEW_CHECKLIST_VERSION,
  };
}
